#!/bin/bash
# =============================================================================
# new-client.sh — Create a new client workspace
# =============================================================================
# Usage: ./scripts/new-client.sh <client-name>
# Example: ./scripts/new-client.sh acme-corp
#
# Creates a fully isolated client workspace with all required directories
# and copies shared system files into the client's config folder.
# =============================================================================

set -euo pipefail

# --- Validate input ---
if [ -z "${1:-}" ]; then
    echo "ERROR: Client name is required."
    echo "Usage: ./scripts/new-client.sh <client-name>"
    echo "Example: ./scripts/new-client.sh acme-corp"
    exit 1
fi

CLIENT_NAME="$1"
# Get the root directory (parent of scripts/)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CLIENT_DIR="$ROOT_DIR/clients/$CLIENT_NAME"

# --- Check if client already exists ---
if [ -d "$CLIENT_DIR" ]; then
    echo "ERROR: Client '$CLIENT_NAME' already exists at $CLIENT_DIR"
    echo "If you want to recreate it, delete the folder first."
    exit 1
fi

echo "============================================="
echo "  Creating client workspace: $CLIENT_NAME"
echo "============================================="

# --- Create directory structure ---
echo "[1/5] Creating directory structure..."

# AI agent directory
mkdir -p "$CLIENT_DIR/.ai/agents"

# Config
mkdir -p "$CLIENT_DIR/config"

# Agent definitions (generated by Bootstrap)
mkdir -p "$CLIENT_DIR/agents"

# Data directories
mkdir -p "$CLIENT_DIR/data/leads"
mkdir -p "$CLIENT_DIR/data/segments"
mkdir -p "$CLIENT_DIR/data/regional/briefs"
mkdir -p "$CLIENT_DIR/data/content/briefs"
mkdir -p "$CLIENT_DIR/data/content/drafts"
mkdir -p "$CLIENT_DIR/data/content/approved"
mkdir -p "$CLIENT_DIR/data/emails/sequences"
mkdir -p "$CLIENT_DIR/data/emails/templates"
mkdir -p "$CLIENT_DIR/data/emails/personalized"
mkdir -p "$CLIENT_DIR/data/emails/approved"
mkdir -p "$CLIENT_DIR/data/pipeline"
mkdir -p "$CLIENT_DIR/data/reports/daily"
mkdir -p "$CLIENT_DIR/data/reports/weekly"
mkdir -p "$CLIENT_DIR/data/reports/monthly"

# Logs
mkdir -p "$CLIENT_DIR/logs/bootstrap"
mkdir -p "$CLIENT_DIR/logs/operations"

# Reviews (for Agent Critic)
mkdir -p "$CLIENT_DIR/reviews/round-1"
mkdir -p "$CLIENT_DIR/reviews/round-2"
mkdir -p "$CLIENT_DIR/reviews/final"

echo "  ✓ Created 25+ directories"

# --- Copy shared system files ---
echo "[2/5] Copying shared system files..."

cp "$ROOT_DIR/system/architecture/shared-schemas.json" "$CLIENT_DIR/config/shared-schemas.json"
cp "$ROOT_DIR/system/architecture/company-profile-template.yaml" "$CLIENT_DIR/config/company-profile.yaml"

echo "  ✓ Copied shared-schemas.json"
echo "  ✓ Copied company-profile-template.yaml → company-profile.yaml"

# --- Create system-architecture.md ---
echo "[3/5] Generating system-architecture.md..."

cat > "$CLIENT_DIR/config/system-architecture.md" << 'SYSARCH'
# System Architecture Reference

## Agent Communication Flow

All agents communicate through structured JSON files. No agent calls another directly.
Coordination goes through Maestro (operational) or Bootstrap Orchestrator (meta).

## Data Flow

```
Discovery Agent → company-profile.yaml
                → discovery-report.md

Regional Coordinator → data/regional/strategy.json
                     → data/regional/briefs/scout-brief-{region}.json

Regional Scout → data/leads/L-YYYY-NNNN.json

Lead Researcher → data/leads/L-YYYY-NNNN.json

Market Intelligence → data/reports/daily/intel-{date}.json

Lead Scorer → updates data/leads/ (fit_score, urgency_score)
            → data/segments/

Analyst → data/reports/daily/{date}.json
        → data/reports/weekly/{date}.json
        → data/reports/monthly/{date}.json

Content Strategist → data/content/briefs/BRF-YYYY-NNNN.json

Copywriter → data/content/drafts/
           → data/emails/templates/

Email Sequence Designer → data/emails/sequences/SEQ-YYYY-NNNN.json

Email Personalizer → data/emails/personalized/L-YYYY-NNNN-step{N}.md

QA Reviewer → data/emails/approved/
            → data/content/approved/

Pipeline Tracker → data/pipeline/status-{date}.json

Scheduler → data/pipeline/send-log-{date}.json
```

## Schema Reference

All schemas are defined in config/shared-schemas.json:
- LeadProfile
- EmailSequenceConfig
- QAReviewReport
- ContentBrief
- PipelineStatusReport
- MarketIntelReport
- DailyAnalyticsReport
- SendLog
- RegionalStrategy
- ScoutBrief
- BootstrapProgress
SYSARCH

echo "  ✓ Generated system-architecture.md"

# --- Create .gitkeep files for empty directories ---
echo "[4/5] Adding .gitkeep files..."

find "$CLIENT_DIR" -type d -empty -exec touch {}/.gitkeep \;

echo "  ✓ Added .gitkeep to empty directories"

# --- Summary ---
echo "[5/5] Finalizing..."
echo ""
echo "============================================="
echo "  Client workspace created successfully!"
echo "============================================="
echo ""
echo "  Location: $CLIENT_DIR"
echo ""
echo "  Next steps:"
echo "  1. cd $CLIENT_DIR"
echo "  2. Run the AI assistant"
echo "  3. Tell Discovery Agent:"
echo "     'Analyze https://client-website.com and build the company profile.'"
echo "  4. Review config/discovery-report.md"
echo "  5. Correct config/company-profile.yaml as needed"
echo "  6. Tell Bootstrap Orchestrator:"
echo "     'Start the bootstrap orchestrator. Generate all 12 marketing agent files.'"
echo "  7. After bootstrap completes, deploy agents:"
echo "     cp agents/*.md .ai/agents/"
echo "  8. Git commit your work"
echo ""
