@echo off
REM =============================================================================
REM new-client.bat — Create a new client workspace
REM =============================================================================
REM Usage: scripts\new-client.bat <client-name>
REM Example: scripts\new-client.bat acme-corp
REM
REM Creates a fully isolated client workspace with all required directories
REM and copies shared system files into the client's config folder.
REM =============================================================================

setlocal enabledelayedexpansion

REM --- Validate input ---
if "%~1"=="" (
    echo ERROR: Client name is required.
    echo Usage: scripts\new-client.bat ^<client-name^>
    echo Example: scripts\new-client.bat acme-corp
    exit /b 1
)

set "CLIENT_NAME=%~1"
set "SCRIPT_DIR=%~dp0"
pushd "%SCRIPT_DIR%.."
set "ROOT_DIR=%CD%"
popd
set "CLIENT_DIR=%ROOT_DIR%\clients\%CLIENT_NAME%"

REM --- Check if client already exists ---
if exist "%CLIENT_DIR%" (
    echo ERROR: Client '%CLIENT_NAME%' already exists at %CLIENT_DIR%
    echo If you want to recreate it, delete the folder first.
    exit /b 1
)

echo =============================================
echo   Creating client workspace: %CLIENT_NAME%
echo =============================================

REM --- Create directory structure ---
echo [1/5] Creating directory structure...

REM AI agent directory
mkdir "%CLIENT_DIR%\.ai\agents"

REM Config
mkdir "%CLIENT_DIR%\config"

REM Agent definitions (generated by Bootstrap)
mkdir "%CLIENT_DIR%\agents"

REM Data directories
mkdir "%CLIENT_DIR%\data\leads"
mkdir "%CLIENT_DIR%\data\segments"
mkdir "%CLIENT_DIR%\data\regional\briefs"
mkdir "%CLIENT_DIR%\data\content\briefs"
mkdir "%CLIENT_DIR%\data\content\drafts"
mkdir "%CLIENT_DIR%\data\content\approved"
mkdir "%CLIENT_DIR%\data\emails\sequences"
mkdir "%CLIENT_DIR%\data\emails\templates"
mkdir "%CLIENT_DIR%\data\emails\personalized"
mkdir "%CLIENT_DIR%\data\emails\approved"
mkdir "%CLIENT_DIR%\data\pipeline"
mkdir "%CLIENT_DIR%\data\reports\daily"
mkdir "%CLIENT_DIR%\data\reports\weekly"
mkdir "%CLIENT_DIR%\data\reports\monthly"

REM Logs
mkdir "%CLIENT_DIR%\logs\bootstrap"
mkdir "%CLIENT_DIR%\logs\operations"

REM Reviews (for Agent Critic)
mkdir "%CLIENT_DIR%\reviews\round-1"
mkdir "%CLIENT_DIR%\reviews\round-2"
mkdir "%CLIENT_DIR%\reviews\final"

echo   + Created 25+ directories

REM --- Copy shared system files ---
echo [2/5] Copying shared system files...

copy "%ROOT_DIR%\system\architecture\shared-schemas.json" "%CLIENT_DIR%\config\shared-schemas.json" >nul
copy "%ROOT_DIR%\system\architecture\company-profile-template.yaml" "%CLIENT_DIR%\config\company-profile.yaml" >nul

echo   + Copied shared-schemas.json
echo   + Copied company-profile-template.yaml -^> company-profile.yaml

REM --- Create system-architecture.md ---
echo [3/5] Generating system-architecture.md...

(
echo # System Architecture Reference
echo.
echo ## Agent Communication Flow
echo.
echo All agents communicate through structured JSON files. No agent calls another directly.
echo Coordination goes through Maestro ^(operational^) or Bootstrap Orchestrator ^(meta^).
echo.
echo ## Data Flow
echo.
echo ```
echo Discovery Agent -^> company-profile.yaml
echo                 -^> discovery-report.md
echo.
echo Regional Coordinator -^> data/regional/strategy.json
echo                      -^> data/regional/briefs/scout-brief-{region}.json
echo.
echo Regional Scout -^> data/leads/L-YYYY-NNNN.json
echo Lead Researcher -^> data/leads/L-YYYY-NNNN.json
echo Market Intelligence -^> data/reports/daily/intel-{date}.json
echo.
echo Lead Scorer -^> updates data/leads/ ^(fit_score, urgency_score^)
echo             -^> data/segments/
echo.
echo Analyst -^> data/reports/daily/{date}.json
echo         -^> data/reports/weekly/{date}.json
echo         -^> data/reports/monthly/{date}.json
echo.
echo Content Strategist -^> data/content/briefs/BRF-YYYY-NNNN.json
echo Copywriter -^> data/content/drafts/
echo            -^> data/emails/templates/
echo.
echo Email Sequence Designer -^> data/emails/sequences/SEQ-YYYY-NNNN.json
echo Email Personalizer -^> data/emails/personalized/L-YYYY-NNNN-step{N}.md
echo.
echo QA Reviewer -^> data/emails/approved/
echo             -^> data/content/approved/
echo.
echo Pipeline Tracker -^> data/pipeline/status-{date}.json
echo Scheduler -^> data/pipeline/send-log-{date}.json
echo ```
echo.
echo ## Schema Reference
echo.
echo All schemas are defined in config/shared-schemas.json:
echo - LeadProfile
echo - EmailSequenceConfig
echo - QAReviewReport
echo - ContentBrief
echo - PipelineStatusReport
echo - MarketIntelReport
echo - DailyAnalyticsReport
echo - SendLog
echo - RegionalStrategy
echo - ScoutBrief
echo - BootstrapProgress
) > "%CLIENT_DIR%\config\system-architecture.md"

echo   + Generated system-architecture.md

REM --- Create .gitkeep files ---
echo [4/5] Adding .gitkeep files...

for /f "delims=" %%d in ('dir /s /b /ad "%CLIENT_DIR%"') do (
    dir /b "%%d" 2>nul | findstr /r "." >nul 2>&1 || (
        type nul > "%%d\.gitkeep"
    )
)

echo   + Added .gitkeep to empty directories

REM --- Summary ---
echo [5/5] Finalizing...
echo.
echo =============================================
echo   Client workspace created successfully!
echo =============================================
echo.
echo   Location: %CLIENT_DIR%
echo.
echo   Next steps:
echo   1. cd %CLIENT_DIR%
echo   2. Run the AI assistant
echo   3. Tell Discovery Agent:
echo      "Analyze https://client-website.com and build the company profile."
echo   4. Review config\discovery-report.md
echo   5. Correct config\company-profile.yaml as needed
echo   6. Tell Bootstrap Orchestrator:
echo      "Start the bootstrap orchestrator. Generate all 12 marketing agent files."
echo   7. After bootstrap completes, deploy agents:
echo      copy agents\*.md .ai\agents\
echo   8. Git commit your work
echo.

endlocal
